<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="abc-PC" name="TestFramework.Tester" tests="1" failures="0" timestamp="2 Sep 2020 06:11:45 GMT" time="0.002" errors="1">
  <testcase name="m1" time="0.002" classname="TestFramework.Tester">
    <error type="java.lang.Error" message="Unresolved compilation problems: 
	locatorValue cannot be resolved to a variable
	locatorType cannot be resolved to a variable
	locatorValue cannot be resolved to a variable
	textToEnter cannot be resolved to a variable
	locatorType cannot be resolved to a variable
	locatorValue cannot be resolved to a variable
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
	locatorValue cannot be resolved to a variable
	locatorType cannot be resolved to a variable
	locatorValue cannot be resolved to a variable
	textToEnter cannot be resolved to a variable
	locatorType cannot be resolved to a variable
	locatorValue cannot be resolved to a variable

	at TestFramework.Tester.m1(Tester.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- m1 -->
</testsuite> <!-- TestFramework.Tester -->
